In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
rounds = os.listdir(f"../data/2026/")
races=list()
for j in rounds:
    races.append(pd.read_csv(f"../data/2026/{j}/laps.csv"))
df = races

In [3]:
n = len(df)
i = 0
races=list()
while i<n:
    races.append(pd.concat([df[i],pd.DataFrame({"Round": [i+1 for _ in range(df[i].shape[0])]})], axis=1))
    i+=1
season = pd.concat(races, axis=0)
season["Season"]=int(2026)
data=season

In [4]:
data=data[(data["PitInTime"].isnull())&(data["PitOutTime"].isnull())].copy()

In [5]:
data.shape

(15128, 33)

In [6]:
from datetime import datetime

In [7]:
def to_seconds(x):
    return x.total_seconds()

In [8]:
colList = data.columns
for item in colList:
    if "time" in item.lower():
        data[item] = pd.to_timedelta(data[item])
        data[item] = data[item].apply(to_seconds)

In [9]:
data

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
0,3486.903,GAS,10,102.591,1.0,1.0,NaN,NaN,NaN,30.332,...,3384.050,NaN,12,5.0,NaN,NaN,False,False,1,2026
1,3585.820,GAS,10,98.917,2.0,1.0,NaN,NaN,26.232,30.273,...,3486.903,NaN,1,5.0,NaN,NaN,False,True,1,2026
2,3684.743,GAS,10,98.923,3.0,1.0,NaN,NaN,26.327,30.046,...,3585.820,NaN,1,5.0,NaN,NaN,False,True,1,2026
3,3783.460,GAS,10,98.717,4.0,1.0,NaN,NaN,26.278,29.879,...,3684.743,NaN,1,5.0,NaN,NaN,False,True,1,2026
4,3881.934,GAS,10,98.474,5.0,1.0,NaN,NaN,26.142,29.826,...,3783.460,NaN,1,5.0,NaN,NaN,False,True,1,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1206,8803.097,BEA,87,76.376,63.0,2.0,NaN,NaN,21.857,24.237,...,8726.721,NaN,1,10.0,NaN,NaN,False,True,14,2026
1207,8879.099,BEA,87,76.002,64.0,2.0,NaN,NaN,21.687,24.222,...,8803.097,NaN,1,10.0,NaN,NaN,False,True,14,2026
1208,8955.288,BEA,87,76.189,65.0,2.0,NaN,NaN,21.844,24.237,...,8879.099,NaN,1,10.0,NaN,NaN,False,True,14,2026
1209,9031.303,BEA,87,76.015,66.0,2.0,NaN,NaN,21.740,24.207,...,8955.288,NaN,1,10.0,NaN,NaN,False,True,14,2026
1210,9107.351,BEA,87,76.048,67.0,2.0,NaN,NaN,21.737,24.172,...,9031.303,NaN,1,10.0,NaN,NaN,False,True,14,2026

In [10]:
data["Compound"].unique()

array(['MEDIUM', 'HARD', 'SOFT', nan, 'INTERMEDIATE'], dtype=object)

In [11]:
data["Compound"].value_counts(dropna=False)

Compound
HARD            7528
MEDIUM          5281
SOFT            2289
NaN               23
INTERMEDIATE       7
Name: count, dtype: int64

In [12]:
data=data[data["Compound"].notna()].copy()

In [13]:
data.shape

(15105, 33)

In [14]:
data[data["Position"].isnull()]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
264,4454.241,STR,18,NaN,10.0,1.0,NaN,NaN,NaN,NaN,...,4304.241,NaN,124,NaN,NaN,NaN,True,False,1,2026
262,7984.527,STR,18,NaN,27.0,2.0,NaN,NaN,NaN,NaN,...,7834.527,NaN,1267,NaN,NaN,NaN,True,False,2,2026
874,4755.504,HAD,6,NaN,11.0,1.0,NaN,NaN,NaN,NaN,...,4605.504,NaN,16,NaN,NaN,NaN,True,False,3,2026
948,5361.898,BOT,77,NaN,16.0,2.0,NaN,NaN,NaN,NaN,...,5211.898,NaN,126,NaN,NaN,NaN,True,False,3,2026
255,8470.248,ANT,12,NaN,62.0,3.0,NaN,NaN,NaN,NaN,...,8320.248,NaN,126,NaN,NaN,NaN,True,False,4,2026
293,6612.613,ALO,14,NaN,38.0,2.0,NaN,NaN,NaN,NaN,...,6462.613,NaN,126,NaN,NaN,NaN,True,False,4,2026
681,3488.742,VER,3,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,3405.791,NaN,1,NaN,NaN,NaN,True,False,5,2026
806,9560.389,OCO,31,NaN,53.0,4.0,NaN,NaN,NaN,NaN,...,9410.389,NaN,126,NaN,NaN,NaN,True,False,5,2026
1106,5939.334,BEA,87,NaN,21.0,2.0,NaN,NaN,NaN,NaN,...,5789.334,NaN,124,NaN,NaN,NaN,True,False,6,2026
1053,5321.480,SAI,55,NaN,24.0,2.0,NaN,NaN,NaN,NaN,...,5171.480,NaN,126,NaN,NaN,NaN,True,False,7,2026
61,3982.714,GAS,10,NaN,5.0,1.0,NaN,NaN,NaN,NaN,...,3832.714,NaN,124,NaN,NaN,NaN,True,False,8,2026
814,3987.709,HAD,6,NaN,5.0,1.0,NaN,NaN,NaN,NaN,...,3837.709,NaN,124,NaN,NaN,NaN,True,False,8,2026
325,4905.488,STR,18,NaN,13.0,1.0,NaN,NaN,NaN,NaN,...,4755.488,NaN,126,NaN,NaN,NaN,True,False,9,2026
420,8834.713,LEC,16,NaN,65.0,4.0,NaN,NaN,NaN,NaN,...,8462.715,NaN,412,NaN,NaN,NaN,True,False,10,2026
477,8834.713,STR,18,NaN,57.0,2.0,NaN,NaN,NaN,NaN,...,7831.627,NaN,124,NaN,NaN,NaN,True,False,10,2026
634,3402.391,VER,3,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,3319.645,NaN,12,NaN,NaN,NaN,True,False,10,2026
1173,11482.821,SAI,55,NaN,71.0,6.0,NaN,NaN,NaN,NaN,...,11332.821,NaN,12,NaN,NaN,NaN,True,False,10,2026
441,7009.230,HUL,27,NaN,37.0,3.0,NaN,NaN,NaN,NaN,...,6859.230,NaN,126,NaN,NaN,NaN,True,False,11,2026
488,7886.501,VER,3,NaN,47.0,3.0,NaN,NaN,NaN,NaN,...,7736.501,NaN,124,NaN,NaN,NaN,True,False,11,2026
1362,8124.377,PIA,81,NaN,56.0,3.0,NaN,NaN,NaN,NaN,...,7974.377,NaN,1267,NaN,NaN,NaN,True,False,12,2026
871,3477.622,RUS,63,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,3355.977,NaN,124,NaN,NaN,NaN,True,False,13,2026
38,6955.765,NOR,1,NaN,39.0,3.0,NaN,NaN,NaN,NaN,...,6805.765,NaN,12,NaN,NaN,NaN,True,False,14,2026
381,4799.197,ALB,23,NaN,12.0,1.0,NaN,NaN,NaN,NaN,...,4649.197,NaN,12,NaN,NaN,NaN,True,False,14,2026
1013,6133.598,RUS,63,NaN,30.0,1.0,NaN,NaN,NaN,NaN,...,5983.598,NaN,126,NaN,NaN,NaN,True,False,14,2026

In [15]:
data.dropna(subset=["Position"], inplace=True)

In [16]:
data.shape

(15081, 33)

In [17]:
data[data["LapTime"].isnull()]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
11,4697.634,GAS,10,NaN,12.0,2.0,NaN,NaN,42.739,44.215,...,4547.651,NaN,4,9.0,NaN,NaN,False,False,1,2026
123,4839.246,ANT,12,NaN,13.0,2.0,NaN,NaN,37.267,44.242,...,4688.728,NaN,41,1.0,NaN,NaN,False,False,1,2026
210,4695.130,LEC,16,NaN,12.0,2.0,NaN,NaN,42.910,44.533,...,4545.025,NaN,4,7.0,NaN,NaN,False,False,1,2026
276,4696.434,HUL,27,NaN,12.0,1.0,NaN,NaN,42.774,44.575,...,4545.516,NaN,4,8.0,NaN,NaN,False,False,1,2026
543,4839.995,COL,43,NaN,13.0,1.0,NaN,NaN,37.203,44.278,...,4689.443,NaN,41,2.0,NaN,NaN,False,False,1,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,3669.287,STR,18,NaN,2.0,1.0,NaN,NaN,36.306,71.217,...,3512.734,NaN,4,16.0,NaN,NaN,False,False,13,2026
835,3825.894,STR,18,NaN,3.0,1.0,NaN,NaN,39.362,71.948,...,3669.287,NaN,4,16.0,NaN,NaN,False,False,13,2026
836,3978.385,STR,18,NaN,4.0,1.0,NaN,NaN,43.833,66.803,...,3825.894,NaN,41,16.0,NaN,NaN,False,False,13,2026
860,3827.891,PER,11,NaN,3.0,2.0,NaN,NaN,38.892,71.916,...,3671.620,NaN,4,18.0,NaN,NaN,False,False,13,2026
861,3979.204,PER,11,NaN,4.0,2.0,NaN,NaN,43.820,66.485,...,3827.891,NaN,41,18.0,NaN,NaN,False,False,13,2026

In [18]:
missing_tyreLife = data[data["TyreLife"].isna()].copy().sort_values(["Season", "Round", "LapNumber"])
missing_tyreLife[
    [
        "Time",
        "Driver",
        "DriverNumber",
        "LapNumber",
        "Position",
        "Stint",
        "PitOutTime",
        "PitInTime",
        "TrackStatus",
        "Deleted",
        "DeletedReason",
        "FastF1Generated",
        "IsAccurate", "Season", "Round"
    ]
].sort_values(["Season", "Round", "LapNumber"])

,Time,Driver,DriverNumber,LapNumber,Position,Stint,PitOutTime,PitInTime,TrackStatus,Deleted,DeletedReason,FastF1Generated,IsAccurate,Season,Round
1216,6802.317,BEA,87,41.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1217,6884.974,BEA,87,42.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1218,6967.393,BEA,87,43.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1219,7050.226,BEA,87,44.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1220,7133.123,BEA,87,45.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1221,7216.364,BEA,87,46.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1222,7300.193,BEA,87,47.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1223,7384.385,BEA,87,48.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1224,7468.311,BEA,87,49.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1225,7552.505,BEA,87,50.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1226,7636.456,BEA,87,51.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1227,7720.585,BEA,87,52.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1228,7805.099,BEA,87,53.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1229,7889.664,BEA,87,54.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1230,7974.306,BEA,87,55.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1231,8062.044,BEA,87,56.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1232,8146.781,BEA,87,57.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1233,8231.160,BEA,87,58.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1234,8315.266,BEA,87,59.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4

In [19]:
for i in range(missing_tyreLife.shape[0]):

    row = missing_tyreLife.iloc[i]

    lap = row["LapNumber"]

    if lap == 1:
        continue

    driver = row["Driver"]
    season = row["Season"]
    round_ = row["Round"]

    current_condition = (
        (data["LapNumber"] == lap) &
        (data["Driver"] == driver) &
        (data["Season"] == season) &
        (data["Round"] == round_)
    )

    previous_condition = (
        (data["LapNumber"] == lap - 1) &
        (data["Driver"] == driver) &
        (data["Season"] == season) &
        (data["Round"] == round_)
    )
    next_condition = (
            (data["LapNumber"] == lap + 1) &
            (data["Driver"] == driver) &
            (data["Season"] == season) &
            (data["Round"] == round_)
        )


    previous = data.loc[previous_condition]
    Next = data.loc[next_condition]


    if previous.empty:
        continue

    previous_tyre_life = (
        previous["TyreLife"].iloc[0]
        if not previous.empty
        else np.nan
    )

    next_tyre_life = (
        Next["TyreLife"].iloc[0]
        if not Next.empty
        else np.nan
    )


    if pd.notna(previous_tyre_life) and pd.notna(next_tyre_life):

        previous_estimate = previous_tyre_life + 1
        next_estimate = next_tyre_life - 1

        if previous_estimate == next_estimate:
            data.loc[current_condition, "TyreLife"] = previous_estimate
            print("edited")

        else:
            data.loc[current_condition, "TyreLife"] = next_estimate
            print("edited")

    elif pd.notna(previous_tyre_life):

        data.loc[current_condition, "TyreLife"] = previous_tyre_life + 1
        print("edited")

    elif pd.notna(next_tyre_life):

        data.loc[current_condition, "TyreLife"] = next_tyre_life - 1
        print("edited")

In [20]:
data[(data["Driver"]=="BEA")&(data["LapNumber"]>=35)&(data["Round"]==4)][
    [
        "Time",
        "Driver",
        "DriverNumber",
        "LapNumber",
        "Position",
        "Stint",
        "PitOutTime",
        "PitInTime",
        "TrackStatus",
        "Deleted",
        "DeletedReason",
        "FastF1Generated",
        "IsAccurate", "Season", "Round"
    ]
]

,Time,Driver,DriverNumber,LapNumber,Position,Stint,PitOutTime,PitInTime,TrackStatus,Deleted,DeletedReason,FastF1Generated,IsAccurate,Season,Round
1210,6243.382,BEA,87,35.0,13.0,2.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1211,6329.284,BEA,87,36.0,13.0,2.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1212,6415.758,BEA,87,37.0,13.0,2.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1213,6502.139,BEA,87,38.0,12.0,2.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1216,6802.317,BEA,87,41.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1217,6884.974,BEA,87,42.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1218,6967.393,BEA,87,43.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1219,7050.226,BEA,87,44.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1220,7133.123,BEA,87,45.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1221,7216.364,BEA,87,46.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1222,7300.193,BEA,87,47.0,15.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1223,7384.385,BEA,87,48.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1224,7468.311,BEA,87,49.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1225,7552.505,BEA,87,50.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1226,7636.456,BEA,87,51.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1227,7720.585,BEA,87,52.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1228,7805.099,BEA,87,53.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1229,7889.664,BEA,87,54.0,14.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1230,7974.306,BEA,87,55.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1231,8062.044,BEA,87,56.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1232,8146.781,BEA,87,57.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1233,8231.160,BEA,87,58.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4
1234,8315.266,BEA,87,59.0,13.0,3.0,NaN,NaN,1,NaN,NaN,False,True,2026,4

In [21]:
data.loc[(data["Driver"]=="BEA")&(data["LapNumber"]>=41)&(data["Round"]==4),"TyreLife"]=(data.loc[(data["Driver"]=="BEA")&(data["LapNumber"]>=41)&(data["Round"]==4),"LapNumber"])-40

In [22]:
missing_tyreLife = data[data["TyreLife"].isna()].copy().sort_values(["Season", "Round", "LapNumber"])
missing_tyreLife[
    [
        "Time",
        "Driver",
        "DriverNumber",
        "LapNumber",
        "Position",
        "Stint",
        "PitOutTime",
        "PitInTime",
        "TrackStatus",
        "Deleted",
        "DeletedReason",
        "FastF1Generated",
        "IsAccurate", "Season", "Round"
    ]
].sort_values(["Season", "Round", "LapNumber"])

Empty DataFrame
Columns: [Time, Driver, DriverNumber, LapNumber, Position, Stint, PitOutTime, PitInTime, TrackStatus, Deleted, DeletedReason, FastF1Generated, IsAccurate, Season, Round]
Index: []

In [23]:
data.to_csv("../data/combined_test.csv")