In [1]:
import numpy as np
import pandas as pd
import os

In [ ]:
df = dict()
year = os.listdir("../data/")
for i in year:
    rounds = os.listdir(f"../data/{i}/")
    races=list()
    for j in rounds:
        races.append(pd.read_csv(f"../data/{i}/{j}/laps.csv"))
    df[i] = races

In [6]:
df

{}

In [7]:
d=df["2021"][0]

KeyError: '2021'

In [ ]:
d[d["IsAccurate"]==False]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:35:08.902000,GAS,10,0 days 00:01:54.003000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:37.569000,...,True,AlphaTauri,0 days 00:33:15.688000,NaN,124,6.0,NaN,NaN,False,False
1,0 days 00:37:31.932000,GAS,10,0 days 00:02:23.030000,2.0,1.0,NaN,NaN,0 days 00:00:43.289000,0 days 00:00:51.176000,...,True,AlphaTauri,0 days 00:35:08.902000,NaN,4,6.0,NaN,NaN,False,False
2,0 days 00:39:52.780000,GAS,10,0 days 00:02:20.848000,3.0,1.0,NaN,NaN,0 days 00:00:42.977000,0 days 00:00:51.004000,...,True,AlphaTauri,0 days 00:37:31.932000,NaN,4,6.0,NaN,NaN,False,False
3,0 days 00:42:17.477000,GAS,10,0 days 00:02:24.697000,4.0,1.0,NaN,NaN,0 days 00:00:42.573000,0 days 00:00:53.772000,...,True,AlphaTauri,0 days 00:39:52.780000,NaN,4,6.0,NaN,NaN,False,False
4,0 days 00:44:41.409000,GAS,10,0 days 00:02:23.932000,5.0,1.0,NaN,NaN,0 days 00:00:41.394000,0 days 00:00:54.989000,...,True,AlphaTauri,0 days 00:42:17.477000,NaN,4,6.0,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096,0 days 01:28:31.277000,GIO,99,0 days 00:02:16.380000,32.0,2.0,NaN,0 days 01:28:26.634000,0 days 00:00:48.761000,0 days 00:00:34.533000,...,True,Alfa Romeo Racing,0 days 01:26:14.897000,NaN,45,11.0,NaN,NaN,False,False
1097,0 days 01:55:02.596000,GIO,99,NaN,33.0,3.0,0 days 01:53:23.075000,0 days 01:54:58.849000,NaN,0 days 00:00:33.243000,...,False,Alfa Romeo Racing,0 days 01:28:31.277000,NaN,51,11.0,NaN,NaN,False,False
1098,0 days 01:57:52.895000,GIO,99,NaN,34.0,4.0,0 days 01:55:59.022000,NaN,0 days 00:01:27.323000,0 days 00:00:35.991000,...,False,Alfa Romeo Racing,0 days 01:55:00.107000,NaN,1,11.0,NaN,NaN,False,False
1104,0 days 02:06:17.376000,GIO,99,0 days 00:01:26.123000,40.0,4.0,NaN,0 days 02:06:13.969000,0 days 00:00:26.128000,0 days 00:00:28.140000,...,False,Alfa Romeo Racing,0 days 02:04:51.253000,NaN,1,12.0,NaN,NaN,False,False
1105,0 days 02:08:00.938000,GIO,99,0 days 00:01:43.562000,41.0,5.0,0 days 02:06:43.656000,NaN,0 days 00:00:48.547000,0 days 00:00:27.947000,...,False,Alfa Romeo Racing,0 days 02:06:17.376000,NaN,1,15.0,NaN,NaN,False,False

In [ ]:
d.groupby("IsAccurate")["PitOutTime"].count()

IsAccurate
False    57
True      0
Name: PitOutTime, dtype: int64

In [ ]:
x = pd.concat([d,pd.DataFrame({"round": [1 for i in range(d.shape[0])]})], axis=1)

In [ ]:
data=pd.DataFrame()
for key, value in df.items():
    n = len(value)
    i = 0
    races=list()
    while i<n:
        races.append(pd.concat([value[i],pd.DataFrame({"Round": [i+1 for _ in range(value[i].shape[0])]})], axis=1))
        i+=1
    season = pd.concat(races, axis=0)
    season["Season"]=int(key)
    data=pd.concat([data, season],axis=0)

In [ ]:
data

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
0,0 days 01:01:19.630000,VER,1,0 days 00:01:35.505000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:29.707000,...,0 days 00:59:43.836000,NaN,1.0,1.0,NaN,NaN,False,False,1,2024
1,0 days 01:02:53.835000,VER,1,0 days 00:01:34.205000,2.0,1.0,NaN,NaN,0 days 00:00:34.720000,0 days 00:00:29.628000,...,0 days 01:01:19.630000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
2,0 days 01:04:27.878000,VER,1,0 days 00:01:34.043000,3.0,1.0,NaN,NaN,0 days 00:00:34.530000,0 days 00:00:29.621000,...,0 days 01:02:53.835000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
3,0 days 01:06:01.632000,VER,1,0 days 00:01:33.754000,4.0,1.0,NaN,NaN,0 days 00:00:34.416000,0 days 00:00:29.541000,...,0 days 01:04:27.878000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
4,0 days 01:07:35.587000,VER,1,0 days 00:01:33.955000,5.0,1.0,NaN,NaN,0 days 00:00:34.457000,0 days 00:00:29.590000,...,0 days 01:06:01.632000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,0 days 02:00:31.740000,GIO,99,0 days 00:00:58.211000,83.0,3.0,NaN,NaN,0 days 00:00:20.437000,0 days 00:00:20.785000,...,0 days 01:59:33.529000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1530,0 days 02:01:29.555000,GIO,99,0 days 00:00:57.815000,84.0,3.0,NaN,NaN,0 days 00:00:20.241000,0 days 00:00:20.663000,...,0 days 02:00:31.740000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1531,0 days 02:02:27.232000,GIO,99,0 days 00:00:57.677000,85.0,3.0,NaN,NaN,0 days 00:00:20.284000,0 days 00:00:20.479000,...,0 days 02:01:29.555000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1532,0 days 02:03:25.043000,GIO,99,0 days 00:00:57.811000,86.0,3.0,NaN,NaN,0 days 00:00:20.230000,0 days 00:00:20.604000,...,0 days 02:02:27.232000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1533,0 days 02:04:23.007000,GIO,99,0 days 00:00:57.964000,87.0,3.0,NaN,NaN,0 days 00:00:20.294000,0 days 00:00:20.673000,...,0 days 02:03:25.043000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020

In [ ]:
data[data["IsAccurate"]==False].count()

Time                  19781
Driver                19781
DriverNumber          19781
LapTime               17348
LapNumber             19781
Stint                 19736
PitOutTime             4892
PitInTime              4933
Sector1Time           16696
Sector2Time           19521
Sector3Time           19367
Sector1SessionTime    16684
Sector2SessionTime    19521
Sector3SessionTime    19367
SpeedI1               19577
SpeedI2               19450
SpeedFL               14647
SpeedST               19502
IsPersonalBest        19633
Compound              19693
TyreLife              19604
FreshTyre             19781
Team                  19781
LapStartTime          19781
LapStartDate              0
TrackStatus           19758
Position              19579
Deleted                   0
DeletedReason             0
FastF1Generated       19781
IsAccurate            19781
Round                 19781
Season                19781
dtype: int64

In [ ]:
data.groupby("IsAccurate")["PitOutTime"].count()

IsAccurate
False    4892
True        0
Name: PitOutTime, dtype: int64

In [ ]:
data.groupby(
    ["Season", "Driver"]
)["IsAccurate"].apply(lambda x: ((~x).mean(), (~x).count()))

Season  Driver
2020    AIT         (0.22988505747126436, 87)
        ALB        (0.17373737373737375, 990)
        BOT        (0.16448032290615539, 991)
        FIT        (0.21428571428571427, 140)
        GAS        (0.16840882694541232, 861)
                             ...
2025    RUS       (0.14979195561719832, 1442)
        SAI       (0.13862179487179488, 1248)
        STR       (0.14350797266514806, 1317)
        TSU       (0.13997113997113997, 1386)
        VER       (0.13818181818181818, 1375)
Name: IsAccurate, Length: 133, dtype: object

In [ ]:
data[(data["PitInTime"].isnull())&(data["PitOutTime"].isnull())]["IsAccurate"].mean()

np.float64(0.9233268598745145)

In [ ]:
data=data[(data["PitInTime"].isnull())&(data["PitOutTime"].isnull())].copy()

In [ ]:
data.dtypes

Time                   object
Driver                 object
DriverNumber            int64
LapTime                object
LapNumber             float64
Stint                 float64
PitOutTime             object
PitInTime              object
Sector1Time            object
Sector2Time            object
Sector3Time            object
Sector1SessionTime     object
Sector2SessionTime     object
Sector3SessionTime     object
SpeedI1               float64
SpeedI2               float64
SpeedFL               float64
SpeedST               float64
IsPersonalBest         object
Compound               object
TyreLife              float64
FreshTyre                bool
Team                   object
LapStartTime           object
LapStartDate          float64
TrackStatus           float64
Position              float64
Deleted               float64
DeletedReason         float64
FastF1Generated          bool
IsAccurate               bool
Round                   int64
Season                  int64
dtype: object

In [ ]:
data.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate', 'Round', 'Season'],
      dtype='object')

In [ ]:
from datetime import datetime

In [ ]:
data

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
0,0 days 01:01:19.630000,VER,1,0 days 00:01:35.505000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:29.707000,...,0 days 00:59:43.836000,NaN,1.0,1.0,NaN,NaN,False,False,1,2024
1,0 days 01:02:53.835000,VER,1,0 days 00:01:34.205000,2.0,1.0,NaN,NaN,0 days 00:00:34.720000,0 days 00:00:29.628000,...,0 days 01:01:19.630000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
2,0 days 01:04:27.878000,VER,1,0 days 00:01:34.043000,3.0,1.0,NaN,NaN,0 days 00:00:34.530000,0 days 00:00:29.621000,...,0 days 01:02:53.835000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
3,0 days 01:06:01.632000,VER,1,0 days 00:01:33.754000,4.0,1.0,NaN,NaN,0 days 00:00:34.416000,0 days 00:00:29.541000,...,0 days 01:04:27.878000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
4,0 days 01:07:35.587000,VER,1,0 days 00:01:33.955000,5.0,1.0,NaN,NaN,0 days 00:00:34.457000,0 days 00:00:29.590000,...,0 days 01:06:01.632000,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,0 days 02:00:31.740000,GIO,99,0 days 00:00:58.211000,83.0,3.0,NaN,NaN,0 days 00:00:20.437000,0 days 00:00:20.785000,...,0 days 01:59:33.529000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1530,0 days 02:01:29.555000,GIO,99,0 days 00:00:57.815000,84.0,3.0,NaN,NaN,0 days 00:00:20.241000,0 days 00:00:20.663000,...,0 days 02:00:31.740000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1531,0 days 02:02:27.232000,GIO,99,0 days 00:00:57.677000,85.0,3.0,NaN,NaN,0 days 00:00:20.284000,0 days 00:00:20.479000,...,0 days 02:01:29.555000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1532,0 days 02:03:25.043000,GIO,99,0 days 00:00:57.811000,86.0,3.0,NaN,NaN,0 days 00:00:20.230000,0 days 00:00:20.604000,...,0 days 02:02:27.232000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1533,0 days 02:04:23.007000,GIO,99,0 days 00:00:57.964000,87.0,3.0,NaN,NaN,0 days 00:00:20.294000,0 days 00:00:20.673000,...,0 days 02:03:25.043000,NaN,1.0,13.0,NaN,NaN,False,True,17,2020

In [ ]:
def to_seconds(x):
    return x.total_seconds()

In [ ]:
colList = data.columns
for item in colList:
    if "time" in item.lower():
        data[item] = pd.to_timedelta(data[item])
        data[item] = data[item].apply(to_seconds)

In [ ]:
data[data["Season"]==2025]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
0,3641.446,PIA,81,98.344,1.0,1.0,NaN,NaN,NaN,28.932,...,3542.863,NaN,12.0,1.0,NaN,NaN,False,False,1,2025
1,3738.997,PIA,81,97.551,2.0,1.0,NaN,NaN,26.193,29.261,...,3641.446,NaN,1.0,1.0,NaN,NaN,False,True,1,2025
2,3836.686,PIA,81,97.689,3.0,1.0,NaN,NaN,26.011,29.486,...,3738.997,NaN,12.0,1.0,NaN,NaN,False,True,1,2025
3,3934.490,PIA,81,97.804,4.0,1.0,NaN,NaN,26.345,29.430,...,3836.686,NaN,1.0,1.0,NaN,NaN,False,True,1,2025
4,4032.572,PIA,81,98.082,5.0,1.0,NaN,NaN,26.312,29.729,...,3934.490,NaN,1.0,1.0,NaN,NaN,False,True,1,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,4914.373,ALO,14,84.224,17.0,1.0,NaN,NaN,27.408,28.672,...,4830.149,NaN,1.0,8.0,NaN,NaN,False,True,24,2025
967,4998.519,ALO,14,84.146,18.0,1.0,NaN,NaN,27.469,28.633,...,4914.373,NaN,1.0,8.0,NaN,NaN,False,True,24,2025
968,5082.704,ALO,14,84.185,19.0,1.0,NaN,NaN,27.425,28.752,...,4998.519,NaN,1.0,8.0,NaN,NaN,False,True,24,2025
971,5360.438,ALO,14,84.078,22.0,2.0,NaN,NaN,27.592,28.716,...,5276.360,NaN,1.0,15.0,NaN,NaN,False,True,24,2025
972,5444.195,ALO,14,83.757,23.0,2.0,NaN,NaN,27.558,28.504,...,5360.438,NaN,1.0,15.0,NaN,NaN,False,True,24,2025

In [ ]:
data["Compound"].unique()

array(['MEDIUM', 'HARD', 'SOFT', 'INTERMEDIATE', 'WET', 'UNKNOWN', nan],
      dtype=object)

In [ ]:
data["Compound"].value_counts()

Compound
HARD            57708
MEDIUM          48824
SOFT            18152
INTERMEDIATE     7876
WET               535
UNKNOWN            20
Name: count, dtype: int64

In [ ]:
data["Compound"].isnull().sum()

np.int64(765)

In [ ]:
data.drop(data[(data["Compound"]=="UNKNOWN")&(data["Compound"].isnull())].index, inplace=True, axis=0)

In [ ]:
data

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
0,3679.630,VER,1,95.505,1.0,1.0,NaN,NaN,NaN,29.707,...,3583.836,NaN,1.0,1.0,NaN,NaN,False,False,1,2024
1,3773.835,VER,1,94.205,2.0,1.0,NaN,NaN,34.720,29.628,...,3679.630,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
2,3867.878,VER,1,94.043,3.0,1.0,NaN,NaN,34.530,29.621,...,3773.835,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
3,3961.632,VER,1,93.754,4.0,1.0,NaN,NaN,34.416,29.541,...,3867.878,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
4,4055.587,VER,1,93.955,5.0,1.0,NaN,NaN,34.457,29.590,...,3961.632,NaN,1.0,1.0,NaN,NaN,False,True,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,7231.740,GIO,99,58.211,83.0,3.0,NaN,NaN,20.437,20.785,...,7173.529,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1530,7289.555,GIO,99,57.815,84.0,3.0,NaN,NaN,20.241,20.663,...,7231.740,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1531,7347.232,GIO,99,57.677,85.0,3.0,NaN,NaN,20.284,20.479,...,7289.555,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1532,7405.043,GIO,99,57.811,86.0,3.0,NaN,NaN,20.230,20.604,...,7347.232,NaN,1.0,13.0,NaN,NaN,False,True,17,2020
1533,7463.007,GIO,99,57.964,87.0,3.0,NaN,NaN,20.294,20.673,...,7405.043,NaN,1.0,13.0,NaN,NaN,False,True,17,2020

In [ ]:
data["IsAccurate"].mean()

np.float64(0.9233268598745145)

In [ ]:
data.drop(columns=['PitOutTime', 'PitInTime', 'LapStartDate', 'TrackStatus', 'Deleted', 'DeletedReason',]).isnull().mean()

Time                  0.000000
Driver                0.000000
DriverNumber          0.000000
LapTime               0.010689
LapNumber             0.000000
Stint                 0.002637
Sector1Time           0.018576
Sector2Time           0.001830
Sector3Time           0.001852
Sector1SessionTime    0.020952
Sector2SessionTime    0.001830
Sector3SessionTime    0.001852
SpeedI1               0.001509
SpeedI2               0.007805
SpeedFL               0.001516
SpeedST               0.001516
IsPersonalBest        0.001105
Compound              0.005714
TyreLife              0.007469
FreshTyre             0.000000
Team                  0.000000
LapStartTime          0.000000
Position              0.001509
FastF1Generated       0.000000
IsAccurate            0.000000
Round                 0.000000
Season                0.000000
dtype: float64

In [ ]:
data[(data["Position"].isnull())]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
206,4219.733,STR,18,NaN,6.0,1.0,NaN,NaN,NaN,NaN,...,4069.733,NaN,124.0,NaN,NaN,NaN,True,False,1,2024
835,3689.352,HAM,44,NaN,2.0,1.0,NaN,NaN,NaN,NaN,...,3539.352,NaN,124.0,NaN,NaN,NaN,True,False,3,2024
767,4937.912,HAM,44,NaN,16.0,2.0,NaN,NaN,NaN,NaN,...,4787.912,NaN,126.0,NaN,NaN,NaN,True,False,7,2024
882,8344.220,RUS,63,NaN,57.0,3.0,NaN,NaN,NaN,NaN,...,8194.220,NaN,126.0,NaN,NaN,NaN,True,False,7,2024
1233,5762.319,OCO,31,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,3305.680,NaN,1254.0,NaN,NaN,NaN,True,False,8,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,2140.792,SAI,55,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,2013.451,NaN,124.0,NaN,NaN,NaN,True,False,15,2020
947,2140.792,STR,18,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,2013.451,NaN,124.0,NaN,NaN,NaN,True,False,15,2020
174,2032.704,LEC,16,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,1963.624,NaN,124.0,NaN,NaN,NaN,True,False,17,2020
697,2032.704,VER,33,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,1963.624,NaN,124.0,NaN,NaN,NaN,True,False,17,2020
1098,5393.428,LAT,6,NaN,53.0,2.0,NaN,NaN,NaN,NaN,...,5243.428,NaN,1267.0,NaN,NaN,NaN,True,False,17,2020

In [ ]:
missing_position = data[data["Position"].isna()].copy()
pd.reset_option("display.max_rows")
missing_position[
    [
        "Time",
        "Driver",
        "DriverNumber",
        "LapNumber",
        "Stint",
        "PitOutTime",
        "PitInTime",
        "TrackStatus",
        "Deleted",
        "DeletedReason",
        "FastF1Generated",
        "IsAccurate", "Season", "Round"
    ]
].sort_values(["Season", "Round"])

,Time,Driver,DriverNumber,LapNumber,Stint,PitOutTime,PitInTime,TrackStatus,Deleted,DeletedReason,FastF1Generated,IsAccurate,Season,Round
460,4359.075,OCO,31,28.0,2.0,NaN,NaN,126.0,NaN,NaN,True,False,2020,2
511,6124.227,VER,33,51.0,2.0,NaN,NaN,124.0,NaN,NaN,True,False,2020,2
878,6324.728,RUS,63,52.0,2.0,NaN,NaN,4.0,NaN,NaN,True,False,2020,2
66,7234.629,GAS,10,67.0,3.0,NaN,NaN,12.0,NaN,NaN,True,False,2020,3
133,7231.593,PER,11,67.0,3.0,NaN,NaN,1.0,NaN,NaN,True,False,2020,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,3492.739,BOR,5,1.0,1.0,NaN,NaN,12.0,NaN,NaN,True,False,2025,18
979,9191.508,SAI,55,68.0,4.0,NaN,NaN,126.0,NaN,NaN,True,False,2025,20
533,7232.944,ALB,23,47.0,2.0,NaN,NaN,12.0,NaN,NaN,True,False,2025,21
793,8667.334,NOR,4,67.0,3.0,NaN,NaN,124.0,NaN,NaN,True,False,2025,21
897,3540.497,GAS,10,1.0,1.0,NaN,NaN,124.0,NaN,NaN,True,False,2025,22

In [ ]:
data["Position"].isna().sum()

np.int64(202)

In [ ]:
data.shape

(133880, 33)

In [ ]:
data = data.dropna(subset=["Position"]).copy()

In [ ]:
data.shape

(133678, 33)

In [ ]:
missing_laptime = data[data["LapTime"].isna()].copy()
missing_laptime[
    [
        "Time",
        "Driver",
        "DriverNumber",
        "LapNumber",
        "Position",
        "Stint",
        "PitOutTime",
        "PitInTime",
        "TrackStatus",
        "Deleted",
        "DeletedReason",
        "FastF1Generated",
        "IsAccurate", "Season", "Round"
    ]
].sort_values(["Season", "Round"])

,Time,Driver,DriverNumber,LapNumber,Position,Stint,PitOutTime,PitInTime,TrackStatus,Deleted,DeletedReason,FastF1Generated,IsAccurate,Season,Round
1140,3071.690,LAT,6,14.0,17.0,1.0,NaN,NaN,1.0,NaN,NaN,False,False,2020,1
796,2985.586,RUS,63,9.0,20.0,1.0,NaN,NaN,1.0,NaN,NaN,False,False,2020,3
841,2981.691,RAI,7,9.0,19.0,1.0,NaN,NaN,1.0,NaN,NaN,False,False,2020,3
10,3300.183,GAS,10,11.0,7.0,1.0,NaN,NaN,4.0,NaN,NaN,False,False,2020,4
11,3470.722,GAS,10,12.0,4.0,1.0,NaN,NaN,4.0,NaN,NaN,False,False,2020,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,3885.648,HUL,27,3.0,15.0,1.0,NaN,NaN,41.0,NaN,NaN,False,False,2025,22
750,3723.415,STR,18,2.0,14.0,1.0,NaN,NaN,4.0,NaN,NaN,False,False,2025,22
751,3885.524,STR,18,3.0,14.0,1.0,NaN,NaN,41.0,NaN,NaN,False,False,2025,22
800,3886.193,DOO,7,3.0,16.0,2.0,NaN,NaN,41.0,NaN,NaN,False,False,2025,22
849,3887.114,BOR,5,3.0,18.0,2.0,NaN,NaN,41.0,NaN,NaN,False,False,2025,22

In [ ]:
missing_laptime[missing_laptime["TrackStatus"]==1]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
2,5775.449,VER,1,NaN,3.0,2.0,NaN,NaN,NaN,42.768,...,5602.630,NaN,1.0,1.0,NaN,NaN,False,False,9,2024
55,5776.440,PER,11,NaN,3.0,2.0,NaN,NaN,NaN,42.877,...,5604.869,NaN,1.0,2.0,NaN,NaN,False,False,9,2024
108,5777.814,SAI,55,NaN,3.0,2.0,NaN,NaN,NaN,43.105,...,5610.557,NaN,1.0,4.0,NaN,NaN,False,False,9,2024
161,5779.875,LEC,16,NaN,3.0,2.0,NaN,NaN,90.624,43.564,...,5626.870,NaN,1.0,7.0,NaN,NaN,False,False,9,2024
214,5777.347,NOR,4,NaN,3.0,2.0,NaN,NaN,NaN,43.152,...,5606.064,NaN,1.0,3.0,NaN,NaN,False,False,9,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,2985.586,RUS,63,NaN,9.0,1.0,NaN,NaN,17.924,31.836,...,2554.246,NaN,1.0,20.0,NaN,NaN,False,False,3,2020
841,2981.691,RAI,7,NaN,9.0,1.0,NaN,NaN,17.477,31.850,...,2552.281,NaN,1.0,19.0,NaN,NaN,False,False,3,2020
648,9335.321,RAI,7,NaN,46.0,7.0,NaN,NaN,60.357,39.413,...,9147.360,NaN,1.0,9.0,NaN,NaN,False,False,11,2020
766,9335.664,GRO,8,NaN,46.0,6.0,NaN,NaN,60.255,38.864,...,9148.846,NaN,1.0,12.0,NaN,NaN,False,False,11,2020
727,11875.669,SAI,55,NaN,48.0,4.0,NaN,NaN,29.941,40.581,...,11781.880,NaN,1.0,7.0,NaN,NaN,False,False,13,2020

In [ ]:
data["TrackStatus"].value_counts()

TrackStatus
1.0       121120
12.0        3934
4.0         3438
41.0        1384
124.0        769
671.0        595
21.0         412
126.0        347
6.0          257
16.0         206
26.0         193
24.0         188
167.0        125
14.0         120
71.0         104
2.0          100
2671.0        73
64.0          73
67.0          51
1267.0        36
412.0         34
264.0         23
1264.0        21
216.0         19
6712.0        12
712.0          8
164.0          7
267.0          3
214.0          1
2167.0         1
1672.0         1
Name: count, dtype: int64

In [ ]:
missing_laptime[
    missing_laptime["TrackStatus"].astype(str).eq("1.0")
]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
2,5775.449,VER,1,NaN,3.0,2.0,NaN,NaN,NaN,42.768,...,5602.630,NaN,1.0,1.0,NaN,NaN,False,False,9,2024
55,5776.440,PER,11,NaN,3.0,2.0,NaN,NaN,NaN,42.877,...,5604.869,NaN,1.0,2.0,NaN,NaN,False,False,9,2024
108,5777.814,SAI,55,NaN,3.0,2.0,NaN,NaN,NaN,43.105,...,5610.557,NaN,1.0,4.0,NaN,NaN,False,False,9,2024
161,5779.875,LEC,16,NaN,3.0,2.0,NaN,NaN,90.624,43.564,...,5626.870,NaN,1.0,7.0,NaN,NaN,False,False,9,2024
214,5777.347,NOR,4,NaN,3.0,2.0,NaN,NaN,NaN,43.152,...,5606.064,NaN,1.0,3.0,NaN,NaN,False,False,9,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,2985.586,RUS,63,NaN,9.0,1.0,NaN,NaN,17.924,31.836,...,2554.246,NaN,1.0,20.0,NaN,NaN,False,False,3,2020
841,2981.691,RAI,7,NaN,9.0,1.0,NaN,NaN,17.477,31.850,...,2552.281,NaN,1.0,19.0,NaN,NaN,False,False,3,2020
648,9335.321,RAI,7,NaN,46.0,7.0,NaN,NaN,60.357,39.413,...,9147.360,NaN,1.0,9.0,NaN,NaN,False,False,11,2020
766,9335.664,GRO,8,NaN,46.0,6.0,NaN,NaN,60.255,38.864,...,9148.846,NaN,1.0,12.0,NaN,NaN,False,False,11,2020
727,11875.669,SAI,55,NaN,48.0,4.0,NaN,NaN,29.941,40.581,...,11781.880,NaN,1.0,7.0,NaN,NaN,False,False,13,2020

keeping position data because removing them can cause polluted value

In [ ]:
missing_tyreLife = data[data["TyreLife"].isna()].copy().sort_values(["Season", "Round", "LapNumber"])
missing_tyreLife[
    [
        "Time",
        "Driver",
        "DriverNumber",
        "LapNumber",
        "Position",
        "Stint",
        "PitOutTime",
        "PitInTime",
        "TrackStatus",
        "Deleted",
        "DeletedReason",
        "FastF1Generated",
        "IsAccurate", "Season", "Round"
    ]
].sort_values(["Season", "Round", "LapNumber"])

,Time,Driver,DriverNumber,LapNumber,Position,Stint,PitOutTime,PitInTime,TrackStatus,Deleted,DeletedReason,FastF1Generated,IsAccurate,Season,Round
1075,5106.520,GRO,8,36.0,13.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
662,5172.109,MAG,20,37.0,9.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
1076,5187.890,GRO,8,37.0,13.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
663,5253.475,MAG,20,38.0,9.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
1077,5268.855,GRO,8,38.0,13.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,5722.273,ALB,23,24.0,6.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
626,5710.603,NOR,4,24.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
771,5726.031,SAI,55,24.0,7.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
885,5721.236,RUS,63,24.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
943,5701.963,PIA,81,24.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11

In [ ]:
for i in range(missing_tyreLife.shape[0]):

    row = missing_tyreLife.iloc[i]

    lap = row["LapNumber"]

    if lap == 1:
        continue

    driver = row["Driver"]
    season = row["Season"]
    round_ = row["Round"]

    current_condition = (
        (data["LapNumber"] == lap) &
        (data["Driver"] == driver) &
        (data["Season"] == season) &
        (data["Round"] == round_)
    )

    previous_condition = (
        (data["LapNumber"] == lap - 1) &
        (data["Driver"] == driver) &
        (data["Season"] == season) &
        (data["Round"] == round_)
    )
    next_condition = (
            (data["LapNumber"] == lap + 1) &
            (data["Driver"] == driver) &
            (data["Season"] == season) &
            (data["Round"] == round_)
        )


    previous = data.loc[previous_condition]
    Next = data.loc[next_condition]


    if previous.empty:
        continue

    previous_tyre_life = (
        previous["TyreLife"].iloc[0]
        if not previous.empty
        else np.nan
    )

    next_tyre_life = (
        Next["TyreLife"].iloc[0]
        if not Next.empty
        else np.nan
    )


    if pd.notna(previous_tyre_life) and pd.notna(next_tyre_life):

        previous_estimate = previous_tyre_life + 1
        next_estimate = next_tyre_life - 1

        if previous_estimate == next_estimate:
            data.loc[current_condition, "TyreLife"] = previous_estimate
            print("edited")

        else:
            data.loc[current_condition, "TyreLife"] = next_estimate
            print("edited")

    elif pd.notna(previous_tyre_life):

        data.loc[current_condition, "TyreLife"] = previous_tyre_life + 1
        print("edited")

    elif pd.notna(next_tyre_life):

        data.loc[current_condition, "TyreLife"] = next_tyre_life - 1
        print("edited")

edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited
edited

In [ ]:
missing_tyreLife = data[data["TyreLife"].isna()].copy().sort_values(["Season", "Round", "LapNumber"])
missing_tyreLife[
    [
        "Time",
        "Driver",
        "DriverNumber",
        "LapNumber",
        "Position",
        "Stint",
        "PitOutTime",
        "PitInTime",
        "TrackStatus",
        "Deleted",
        "DeletedReason",
        "FastF1Generated",
        "IsAccurate", "Season", "Round"
    ]
].sort_values(["Season", "Round", "LapNumber"])

,Time,Driver,DriverNumber,LapNumber,Position,Stint,PitOutTime,PitInTime,TrackStatus,Deleted,DeletedReason,FastF1Generated,IsAccurate,Season,Round
1075,5106.520,GRO,8,36.0,13.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
662,5172.109,MAG,20,37.0,9.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
1076,5187.890,GRO,8,37.0,13.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
663,5253.475,MAG,20,38.0,9.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
1077,5268.855,GRO,8,38.0,13.0,2.0,NaN,NaN,1.0,NaN,NaN,False,True,2020,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,5633.185,SAI,55,23.0,7.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
884,5628.696,RUS,63,23.0,5.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
942,5610.534,PIA,81,23.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
137,5719.924,ANT,12,24.0,4.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11
771,5726.031,SAI,55,24.0,7.0,NaN,NaN,NaN,1.0,NaN,NaN,False,True,2025,11

remaining missing are the rows with:
- previous/next lap is also missing,
- a stint/tyre change occurs around the missing lap,
- the adjacent lap isn't available,
- or the underlying FastF1 data genuinely doesn't give enough information.

In [ ]:
data.drop(columns=['PitOutTime', 'PitInTime', 'LapStartDate', 'TrackStatus', 'Deleted', 'DeletedReason',]).isnull().mean()

Time                  0.000000
Driver                0.000000
DriverNumber          0.000000
LapTime               0.009194
LapNumber             0.000000
Stint                 0.002641
Sector1Time           0.017093
Sector2Time           0.000322
Sector3Time           0.000344
Sector1SessionTime    0.019472
Sector2SessionTime    0.000322
Sector3SessionTime    0.000344
SpeedI1               0.000000
SpeedI2               0.006306
SpeedFL               0.000007
SpeedST               0.000007
IsPersonalBest        0.000000
Compound              0.005715
TyreLife              0.007324
FreshTyre             0.000000
Team                  0.000000
LapStartTime          0.000000
Position              0.000000
FastF1Generated       0.000000
IsAccurate            0.000000
Round                 0.000000
Season                0.000000
dtype: float64

In [ ]:
missing_tyreLife = data[data["Compound"].isna()].copy().sort_values(["Season", "Round", "LapNumber"])
print(missing_tyreLife.shape)
missing_tyreLife[
    [
        "Driver",
        "LapNumber",
         "Season", "Round"
    ]
].sort_values(["Season", "Round","Driver", "LapNumber"]).head(60)

(0, 33)

Empty DataFrame
Columns: [Driver, LapNumber, Season, Round]
Index: []

In [ ]:
data["Compound"].value_counts(dropna=False)

Compound
HARD            58182
MEDIUM          48930
SOFT            18159
INTERMEDIATE     7852
WET               535
UNKNOWN            20
Name: count, dtype: int64

# manual filling

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==5) & (data["Driver"]=="STR") & (data["LapNumber"]>=31) & (data["LapNumber"]<=64)
data.loc[condition,"Compound"] = "MEDIUM"

In [ ]:
data[condition]["Compound"]

350    MEDIUM
351    MEDIUM
352    MEDIUM
353    MEDIUM
354    MEDIUM
355    MEDIUM
356    MEDIUM
357    MEDIUM
358    MEDIUM
359    MEDIUM
360    MEDIUM
361    MEDIUM
362    MEDIUM
363    MEDIUM
364    MEDIUM
365    MEDIUM
366    MEDIUM
367    MEDIUM
368    MEDIUM
369    MEDIUM
370    MEDIUM
371    MEDIUM
372    MEDIUM
373    MEDIUM
374    MEDIUM
375    MEDIUM
376    MEDIUM
377    MEDIUM
378    MEDIUM
379    MEDIUM
380    MEDIUM
381    MEDIUM
382    MEDIUM
383    MEDIUM
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="ALB") & (data["LapNumber"]>=43) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "SOFT"

In [ ]:
data[condition]["Compound"]

558    SOFT
559    SOFT
560    SOFT
561    SOFT
562    SOFT
563    SOFT
564    SOFT
565    SOFT
566    SOFT
567    SOFT
568    SOFT
569    SOFT
570    SOFT
571    SOFT
572    SOFT
573    SOFT
574    SOFT
575    SOFT
576    SOFT
577    SOFT
578    SOFT
579    SOFT
580    SOFT
581    SOFT
582    SOFT
583    SOFT
584    SOFT
585    SOFT
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="BOT") & (data["LapNumber"]>=41) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "HARD"

In [ ]:
data[condition]["Compound"]

1294    HARD
1295    HARD
1296    HARD
1297    HARD
1298    HARD
1299    HARD
1300    HARD
1301    HARD
1302    HARD
1303    HARD
1304    HARD
1305    HARD
1306    HARD
1307    HARD
1308    HARD
1309    HARD
1310    HARD
1311    HARD
1312    HARD
1313    HARD
1314    HARD
1315    HARD
1316    HARD
1317    HARD
1318    HARD
1319    HARD
1320    HARD
1321    HARD
1322    HARD
1323    HARD
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="LAT") & (data["LapNumber"]>=37) & (data["LapNumber"]<=47)
data.loc[condition,"Compound"] = "SOFT"

In [ ]:
data[condition]["Compound"]

1171    SOFT
1172    SOFT
1173    SOFT
1174    SOFT
1175    SOFT
1176    SOFT
1177    SOFT
1178    SOFT
1179    SOFT
1180    SOFT
1181    SOFT
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="MAG") & (data["LapNumber"]>=43) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "MEDIUM"

In [ ]:
data[condition]["Compound"]

418    MEDIUM
419    MEDIUM
420    MEDIUM
421    MEDIUM
422    MEDIUM
423    MEDIUM
424    MEDIUM
425    MEDIUM
426    MEDIUM
427    MEDIUM
428    MEDIUM
429    MEDIUM
430    MEDIUM
431    MEDIUM
432    MEDIUM
433    MEDIUM
434    MEDIUM
435    MEDIUM
436    MEDIUM
437    MEDIUM
438    MEDIUM
439    MEDIUM
440    MEDIUM
441    MEDIUM
442    MEDIUM
443    MEDIUM
444    MEDIUM
445    MEDIUM
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="MSC") & (data["LapNumber"]>=45) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "MEDIUM"

In [ ]:
data[condition]["Compound"]

982     MEDIUM
983     MEDIUM
984     MEDIUM
985     MEDIUM
986     MEDIUM
987     MEDIUM
988     MEDIUM
989     MEDIUM
990     MEDIUM
991     MEDIUM
992     MEDIUM
993     MEDIUM
994     MEDIUM
995     MEDIUM
996     MEDIUM
997     MEDIUM
998     MEDIUM
999     MEDIUM
1000    MEDIUM
1001    MEDIUM
1002    MEDIUM
1003    MEDIUM
1004    MEDIUM
1005    MEDIUM
1006    MEDIUM
1007    MEDIUM
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="NOR") & (data["LapNumber"]>=45) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "HARD"

In [ ]:
data[condition]["Compound"]

841    HARD
842    HARD
843    HARD
844    HARD
845    HARD
846    HARD
847    HARD
848    HARD
849    HARD
850    HARD
851    HARD
852    HARD
853    HARD
854    HARD
855    HARD
856    HARD
857    HARD
858    HARD
859    HARD
860    HARD
861    HARD
862    HARD
863    HARD
864    HARD
865    HARD
866    HARD
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="OCO") & (data["LapNumber"]>=46) & (data["LapNumber"]<=71)
data.loc[condition,"Compound"] = "HARD"

In [ ]:
data[condition]["Compound"]

771    HARD
772    HARD
773    HARD
774    HARD
775    HARD
776    HARD
777    HARD
778    HARD
779    HARD
780    HARD
781    HARD
782    HARD
783    HARD
784    HARD
785    HARD
786    HARD
787    HARD
788    HARD
789    HARD
790    HARD
791    HARD
792    HARD
793    HARD
794    HARD
795    HARD
796    HARD
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="RIC") & (data["LapNumber"]>=46) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "HARD"

In [ ]:
data[condition]["Compound"]

701    HARD
702    HARD
703    HARD
704    HARD
705    HARD
706    HARD
707    HARD
708    HARD
709    HARD
710    HARD
711    HARD
712    HARD
713    HARD
714    HARD
715    HARD
716    HARD
717    HARD
718    HARD
719    HARD
720    HARD
721    HARD
722    HARD
723    HARD
724    HARD
725    HARD
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="RUS") & (data["LapNumber"]>=42) & (data["LapNumber"]<=71)
data.loc[condition,"Compound"] = "MEDIUM"

In [ ]:
data[condition]["Compound"]

1224    MEDIUM
1225    MEDIUM
1226    MEDIUM
1227    MEDIUM
1228    MEDIUM
1229    MEDIUM
1230    MEDIUM
1231    MEDIUM
1232    MEDIUM
1233    MEDIUM
1234    MEDIUM
1235    MEDIUM
1236    MEDIUM
1237    MEDIUM
1238    MEDIUM
1239    MEDIUM
1240    MEDIUM
1241    MEDIUM
1242    MEDIUM
1243    MEDIUM
1244    MEDIUM
1245    MEDIUM
1246    MEDIUM
1247    MEDIUM
1248    MEDIUM
1249    MEDIUM
1250    MEDIUM
1251    MEDIUM
1252    MEDIUM
1253    MEDIUM
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="SAI") & (data["LapNumber"]>=52) & (data["LapNumber"]<=56)
data.loc[condition,"Compound"] = "SOFT"

In [ ]:
data[condition]["Compound"]

1129    SOFT
1130    SOFT
1131    SOFT
1132    SOFT
1133    SOFT
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2022) & (data["Round"]==13) & (data["Driver"]=="VET") & (data["LapNumber"]>=46) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "MEDIUM"

In [ ]:
data[condition]["Compound"]

1053    MEDIUM
1054    MEDIUM
1055    MEDIUM
1056    MEDIUM
1057    MEDIUM
1058    MEDIUM
1059    MEDIUM
1060    MEDIUM
1061    MEDIUM
1062    MEDIUM
1063    MEDIUM
1064    MEDIUM
1065    MEDIUM
1066    MEDIUM
1067    MEDIUM
1068    MEDIUM
1069    MEDIUM
1070    MEDIUM
1071    MEDIUM
1072    MEDIUM
1073    MEDIUM
1074    MEDIUM
1075    MEDIUM
1076    MEDIUM
1077    MEDIUM
Name: Compound, dtype: object

In [ ]:
condition = (data["Season"]==2023) & (data["Round"]==8) & (data["Driver"]=="TSU") & (data["LapNumber"]>=36) & (data["LapNumber"]<=70)
data.loc[condition,"Compound"] = "MEDIUM"

In [ ]:
data[condition]["Compound"]

600    MEDIUM
601    MEDIUM
602    MEDIUM
603    MEDIUM
604    MEDIUM
605    MEDIUM
606    MEDIUM
607    MEDIUM
608    MEDIUM
609    MEDIUM
610    MEDIUM
611    MEDIUM
612    MEDIUM
613    MEDIUM
614    MEDIUM
615    MEDIUM
616    MEDIUM
617    MEDIUM
618    MEDIUM
619    MEDIUM
620    MEDIUM
621    MEDIUM
622    MEDIUM
623    MEDIUM
624    MEDIUM
625    MEDIUM
626    MEDIUM
627    MEDIUM
628    MEDIUM
629    MEDIUM
630    MEDIUM
631    MEDIUM
632    MEDIUM
633    MEDIUM
634    MEDIUM
Name: Compound, dtype: object

In [ ]:
data["Compound"].fillna(data["Compound"].mode()[0], inplace=True)

# continue...

In [ ]:
data.to_csv("../data/combined.csv")