In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../data/combined.csv")
print(df.shape)
df.sample(10)

(133678, 34)

,Unnamed: 0,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,...,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Round,Season
76917,339,7984.645,TSU,22,108.618,37.0,2.0,NaN,NaN,38.927,...,7876.027,NaN,1.0,6.0,NaN,NaN,False,True,8,2022
32789,1251,6429.885,MAZ,9,72.006,61.0,2.0,NaN,NaN,17.872,...,6357.879,NaN,1.0,17.0,NaN,NaN,False,True,8,2021
11013,46,4599.867,VER,1,82.905,47.0,3.0,NaN,NaN,24.960,...,4516.962,NaN,1.0,2.0,NaN,NaN,False,True,12,2024
120796,300,5118.213,GAS,10,82.582,37.0,2.0,NaN,NaN,24.091,...,5035.631,NaN,1.0,8.0,NaN,NaN,False,True,5,2020
78567,62,6138.497,GAS,10,115.471,19.0,2.0,NaN,NaN,32.507,...,6023.026,NaN,1.0,11.0,NaN,NaN,False,True,10,2022
13220,1139,3918.953,ZHO,24,72.089,8.0,1.0,NaN,NaN,18.003,...,3846.864,NaN,1.0,18.0,NaN,NaN,False,True,13,2024
108940,44,7016.477,VER,1,73.844,45.0,3.0,NaN,NaN,18.844,...,6942.633,NaN,1.0,4.0,NaN,NaN,False,True,18,2025
24302,344,5684.527,RUS,63,83.732,27.0,2.0,NaN,NaN,27.426,...,5600.795,NaN,1.0,8.0,NaN,NaN,False,True,24,2024
117221,677,4904.552,KVY,26,69.073,40.0,2.0,NaN,NaN,17.574,...,4835.479,NaN,1.0,12.0,NaN,NaN,False,True,1,2020
69659,11,4890.079,VER,1,95.191,12.0,1.0,NaN,NaN,35.303,...,4794.888,NaN,1.0,3.0,NaN,NaN,False,True,1,2022

In [3]:
df.columns

Index(['Unnamed: 0', 'Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber',
       'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time',
       'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime',
       'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST',
       'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team',
       'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted',
       'DeletedReason', 'FastF1Generated', 'IsAccurate', 'Round', 'Season'],
      dtype='object')

In [4]:
df = df[['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber',
       'Stint', 'Compound', 'TyreLife', 'Team',
       'LapStartTime', 'TrackStatus', 'Position', "Round", 'Season']].copy()

In [5]:
df["TrackStatus"]=df["TrackStatus"].astype(str)

In [6]:
df["TrackStatus"]

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ...
133673    1.0
133674    1.0
133675    1.0
133676    1.0
133677    1.0
Name: TrackStatus, Length: 133678, dtype: object

In [7]:
df["is_clear"] = df["TrackStatus"].str.contains("1").astype(int)
df["is_yellow"] = df["TrackStatus"].str.contains("2").astype(int)
df["is_unknown"] = df["TrackStatus"].str.contains("3").astype(int)
df["is_SC"] = df["TrackStatus"].str.contains("4").astype(int)
df["is_red"] = df["TrackStatus"].str.contains("5").astype(int)
df["is_vsc"] = df["TrackStatus"].str.contains("6").astype(int)
df["is_vscEnding"] = df["TrackStatus"].str.contains("7").astype(int)

In [8]:
for i in df["Season"].unique(): 
    for j in df.loc[df["Season"]==i,"Round"].unique():
        minTime=df.loc[(df["Season"]==i)&(df["Round"]==j),"LapStartTime"].min()
        df.loc[(df["Season"]==i)&(df["Round"]==j),"LapStartTime"]=df.loc[(df["Season"]==i)&(df["Round"]==j),"LapStartTime"]-minTime

In [9]:
for i in df["Season"].unique(): 
    for j in df.loc[df["Season"]==i,"Round"].unique():
        minTime=df.loc[(df["Season"]==i)&(df["Round"]==j),"Time"].min()
        df.loc[(df["Season"]==i)&(df["Round"]==j),"Time"]=df.loc[(df["Season"]==i)&(df["Round"]==j),"Time"]-minTime

In [10]:
df.loc[(df["Season"]==2023)&(df["Round"]==13)].sort_values(["LapNumber"]).head(60)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Compound,TyreLife,Team,LapStartTime,...,Position,Round,Season,is_clear,is_yellow,is_unknown,is_SC,is_red,is_vsc,is_vscEnding
59847,0.000,VER,1,87.912,1.0,1.0,MEDIUM,4.0,Red Bull Racing,0.000,...,1.0,13,2023,1,1,0,0,0,0,0
60961,9.516,SAR,2,97.428,1.0,1.0,MEDIUM,1.0,Williams,0.000,...,17.0,13,2023,1,1,0,0,0,0,0
59913,1.989,NOR,4,89.901,1.0,1.0,MEDIUM,1.0,McLaren,0.000,...,3.0,13,2023,1,1,0,0,0,0,0
60177,8.110,RUS,63,96.022,1.0,1.0,HARD,1.0,Mercedes,0.000,...,14.0,13,2023,1,1,0,0,0,0,0
60636,10.205,RIC,3,98.117,1.0,1.0,MEDIUM,4.0,AlphaTauri,0.000,...,18.0,13,2023,1,1,0,0,0,0,0
60701,5.677,HUL,27,93.589,1.0,1.0,MEDIUM,4.0,Haas F1 Team,0.000,...,9.0,13,2023,1,1,0,0,0,0,0
60441,6.193,STR,18,94.105,1.0,1.0,SOFT,1.0,Aston Martin,0.000,...,10.0,13,2023,1,1,0,0,0,0,0
60896,7.871,MAG,20,95.783,1.0,1.0,MEDIUM,1.0,Haas F1 Team,0.000,...,13.0,13,2023,1,1,0,0,0,0,0
60309,3.872,SAI,55,91.784,1.0,1.0,SOFT,1.0,Ferrari,0.000,...,6.0,13,2023,1,1,0,0,0,0,0
59979,5.156,PER,11,93.068,1.0,1.0,HARD,4.0,Red Bull Racing,0.000,...,8.0,13,2023,1,1,0,0,0,0,0
61023,19.103,OCO,31,106.965,1.0,1.0,MEDIUM,4.0,Alpine,0.000,...,19.0,13,2023,1,1,0,0,0,0,0
60243,3.416,LEC,16,91.328,1.0,1.0,MEDIUM,4.0,Ferrari,0.000,...,5.0,13,2023,1,1,0,0,0,0,0
60506,8.641,ALB,23,96.553,1.0,1.0,MEDIUM,1.0,Williams,0.000,...,15.0,13,2023,1,1,0,0,0,0,0
60111,0.772,PIA,81,88.684,1.0,1.0,MEDIUM,3.0,McLaren,0.000,...,2.0,13,2023,1,1,0,0,0,0,0
60045,2.627,HAM,44,90.539,1.0,1.0,MEDIUM,4.0,Mercedes,0.000,...,4.0,13,2023,1,1,0,0,0,0,0
60831,8.821,ZHO,24,96.733,1.0,1.0,MEDIUM,4.0,Alfa Romeo,0.000,...,16.0,13,2023,1,1,0,0,0,0,0
60571,7.326,BOT,77,95.238,1.0,1.0,MEDIUM,4.0,Alfa Romeo,0.000,...,12.0,13,2023,1,1,0,0,0,0,0
60766,6.918,TSU,22,94.830,1.0,1.0,SOFT,1.0,AlphaTauri,0.000,...,11.0,13,2023,1,1,0,0,0,0,0
60375,4.659,ALO,14,92.571,1.0,1.0,MEDIUM,4.0,Aston Martin,0.000,...,7.0,13,2023,1,1,0,0,0,0,0
60832,96.753,ZHO,24,87.932,2.0,1.0,MEDIUM,5.0,Alfa Romeo,96.979,...,16.0,13,2023,1,0,0,0,0,0,0
60897,95.642,MAG,20,87.771,2.0,1.0,MEDIUM,2.0,Haas F1 Team,96.029,...,14.0,13,2023,1,0,0,0,0,0,0
59980,91.926,PER,11,86.770,2.0,1.0,HARD,5.0,Red Bull Racing,93.314,...,8.0,13,2023,1,0,0,0,0,0,0
60962,97.390,SAR,2,87.874,2.0,1.0,MEDIUM,2.0,Williams,97.674,...,17.0,13,2023,1,0,0,0,0,0,0
60507,96.171,ALB,23,87.530,2.0,1.0,MEDIUM,2.0,Williams,96.799,...,15.0,13,2023,1,0,0,0,0,0,0
60112,86.389,PIA,81,85.617,2.0,1.0,MEDIUM,4.0,McLaren,88.930,...,2.0,13,2023,1,0,0,0,0,0,0
60310,90.102,SAI,55,86.230,2.0,1.0,SOFT,2.0,Ferrari,92.030,...,6.0,13,2023,1,0,0,0,0,0,0
60637,98.103,RIC,3,87.898,2.0,1.0,MEDIUM,5.0,AlphaTauri,98.363,...,18.0,13,2023,1,0,0,0,0,0,0
59914,87.809,NOR,4,85.820,2.0,1.0,MEDIUM,2.0,McLaren,90.147,...,3.0,13,2023,1,0,0,0,0,0,0
60178,94.882,RUS,63,86.772,2.0,1.0,HARD,2.0,Mercedes,96.268,...,13.0,13,2023,1,0,0,0,0,0,0
59848,85.157,VER,1,85.157,2.0,1.0,MEDIUM,5.0,Red Bull Racing,88.158,...,1.0,13,2023,1,0,0,0,0,0,0
60442,93.195,STR,18,87.002,2.0,1.0,SOFT,2.0,Aston Martin,94.351,...,10.0,13,2023,1,0,0,0,0,0,0
60702,92.579,HUL,27,86.902,2.0,1.0,MEDIUM,5.0,Haas F1 Team,93.835,...,9.0,13,2023,1,0,0,0,0,0,0
60767,93.935,TSU,22,87.017,2.0,1.0,SOFT,2.0,AlphaTauri,95.076,...,11.0,13,2023,1,0,0,0,0,0,0
60376,91.540,ALO,14,86.881,2.0,1.0,MEDIUM,5.0,Aston Martin,92.817,...,7.0,13,2023,1,0,0,0,0,0,0
60572,94.417,BOT,77,87.091,2.0,1.0,MEDIUM,5.0,Alfa Romeo,95.484,...,12.0,13,2023,1,0,0,0,0,0,0
60244,89.752,LEC,16,86.336,2.0,1.0,MEDIUM,5.0,Ferrari,91.574,...,5.0,13,2023,1,0,0,0,0,0,0
60046,88.679,HAM,44,86.052,2.0,1.0,MEDIUM,5.0,Mercedes,90.785,...,4.0,13,2023,1,0,0,0,0,0,0
59981,178.196,PER,11,86.270,3.0,1.0,HARD,6.0,Red Bull Racing,180.084,...,8.0,13,2023,1,0,0,0,0,0,0
60898,182.399,MAG,20,86.757,3.0,1.0,MEDIUM,3.0,Haas F1 Team,183.800,...,14.0,13,2023,1,0,0,0,0,0,0
60311,176.164,SAI,55,86.062,3.0,1.0,SOFT,3.0,Ferrari,178.260,...,6.0,13,2023,1,0,0,0,0,0,0
60443,179.453,STR,18,86.258,3.0,1.0,SOFT,3.0,Aston Martin,181.353,...,10.0,13,2023,1,0,0,0,0,0,0
60179,181.719,RUS,63,86.837,3.0,1.0,HARD,3.0,Mercedes,183.040,...,13.0,13,2023,1,0,0,0,0,0,0
59915,173.014,NOR,4,85.205,3.0,1.0,MEDIUM,3.0,McLaren,175.967,...,3.0,13,2023,1,0,0,0,0,0,0
60638,184.981,RIC,3,86.878,3.0,1.0,MEDIUM,6.0,AlphaTauri,186.261,...,18.0,13,2023,1,0,0,0,0,0,0
60047,174.106,HAM,44,85.427,3.0,1.0,MEDIUM,6.0,Mercedes,176.837,...,4.0,13,2023,1,0,0,0,0,0,0
60768,180.308,TSU,22,86.373,3.0,1.0,SOFT,3.0,AlphaTauri,182.093,...,11.0,13,2023,1,0,0,0,0,0,0
60377,177.452,ALO,14,85.912,3.0,1.0,MEDIUM,6.0,Aston Martin,179.698,...,7.0,13,2023,1,0,0,0,0,0,0
60963,184.216,SAR,2,86.826,3.0,1.0,MEDIUM,3.0,Williams,185.548,...,17.0,13,2023,1,0,0,0,0,0,0
60245,175.401,LEC,16,85.649,3.0,1.0,MEDIUM,6.0,Ferrari,177.910,...,5.0,13,2023,1,0,0,0,0,0,0
60573,180.942,BOT,77,86.525,3.0,1.0,MEDIUM,6.0,Alfa Romeo,182.575,...,12.0,13,2023,1,0,0,0,0,0,0
60508,182.967,ALB,23,86.796,3.0,1.0,MEDIUM,3.0,Williams,184.329,...,15.0,13,2023,1,0,0,0,0,0,0
59849,170.227,VER,1,85.070,3.0,1.0,MEDIUM,6.0,Red Bull Racing,173.315,...,1.0,13,2023,1,0,0,0,0,0,0
60703,178.888,HUL,27,86.309,3.0,1.0,MEDIUM,6.0,Haas F1 Team,180.737,...,9.0,13,2023,1,0,0,0,0,0,0
60113,171.504,PIA,81,85.115,3.0,1.0,MEDIUM,5.0,McLaren,174.547,...,2.0,13,2023,1,0,0,0,0,0,0
60833,183.527,ZHO,24,86.774,3.0,1.0,MEDIUM,6.0,Alfa Romeo,184.911,...,16.0,13,2023,1,0,0,0,0,0,0
60899,268.498,MAG,20,86.099,4.0,1.0,MEDIUM,4.0,Haas F1 Team,270.557,...,14.0,13,2023,1,0,0,0,0,0,0
59850,254.769,VER,1,84.542,4.0,1.0,MEDIUM,7.0,Red Bull Racing,258.385,...,1.0,13,2023,1,0,0,0,0,0,0
59916,257.808,NOR,4,84.794,4.0,1.0,MEDIUM,4.0,McLaren,261.172,...,3.0,13,2023,1,0,0,0,0,0,0
60114,256.389,PIA,81,84.885,4.0,1.0,MEDIUM,6.0,McLaren,259.662,...,2.0,13,2023,1,0,0,0,0,0,0
60509,269.205,ALB,23,86.238,4.0,1.0,MEDIUM,4.0,Williams,271.125,...,15.0,13,2023,1,0,0,0,0,0,0

In [11]:
df.drop(columns=["LapStartTime","TrackStatus"], inplace=True)

In [12]:
def get_mean_lap_time(df):
    if df.empty or "LapTime" not in df.columns:
        return np.nan

    values = df["LapTime"].dropna()

    if values.empty:
        return np.nan

    return values.mean()


def get_median_lap_time(df):
    if df.empty or "LapTime" not in df.columns:
        return np.nan

    values = df["LapTime"].dropna()

    if values.empty:
        return np.nan

    return values.median()

In [13]:
def create_data_for_round(data):

    rows=[]
    laps = data["LapNumber"].dropna().unique()

    for lap in laps:

        if lap < 5:
            continue

        if lap > data["LapNumber"].max() - 5:
            break

        for driver in data[data["LapNumber"] == lap]["Driver"].unique():


            current = data[
                (data["LapNumber"] == lap) &
                (data["Driver"] == driver)
            ]

            if current.empty:
                continue

            current = current.iloc[0]

            Driver = driver
            Position = current["Position"]
            Time = current["Time"]
            Team = current["Team"]
            Compound = current["Compound"]
            TyreLife = current["TyreLife"]
            LapTime = current["LapTime"]

            if pd.isna(Position):
                continue

            Position = int(Position)


            p = data[
                (data["LapNumber"] <= lap) &
                (data["LapNumber"] > lap - 5) &
                (data["Driver"] == driver)
            ]

            if p["LapTime"].notna().sum() < 4:
                continue


            p_minus1_driver = data[
                (data["LapNumber"] == lap) &
                (data["Position"] == Position - 1)
            ]["Driver"]

            p_minus2_driver = data[
                (data["LapNumber"] == lap) &
                (data["Position"] == Position - 2)
            ]["Driver"]

            p_minus3_driver = data[
                (data["LapNumber"] == lap) &
                (data["Position"] == Position - 3)
            ]["Driver"]

            p_plus1_driver = data[
                (data["LapNumber"] == lap) &
                (data["Position"] == Position + 1)
            ]["Driver"]

            p_plus2_driver = data[
                (data["LapNumber"] == lap) &
                (data["Position"] == Position + 2)
            ]["Driver"]

            p_plus3_driver = data[
                (data["LapNumber"] == lap) &
                (data["Position"] == Position + 3)
            ]["Driver"]

            p_minus1_driver = (
                p_minus1_driver.iloc[0]
                if not p_minus1_driver.empty
                else None
            )

            p_minus2_driver = (
                p_minus2_driver.iloc[0]
                if not p_minus2_driver.empty
                else None
            )

            p_minus3_driver = (
                p_minus3_driver.iloc[0]
                if not p_minus3_driver.empty
                else None
            )

            p_plus1_driver = (
                p_plus1_driver.iloc[0]
                if not p_plus1_driver.empty
                else None
            )

            p_plus2_driver = (
                p_plus2_driver.iloc[0]
                if not p_plus2_driver.empty
                else None
            )

            p_plus3_driver = (
                p_plus3_driver.iloc[0]
                if not p_plus3_driver.empty
                else None
            )


            p_minus1 = data[
                (data["Driver"] == p_minus1_driver) &
                (data["LapNumber"] <= lap) &
                (data["LapNumber"] > lap - 5)
            ].copy() if p_minus1_driver is not None else data.iloc[0:0].copy()

            p_minus2 = data[
                (data["Driver"] == p_minus2_driver) &
                (data["LapNumber"] <= lap) &
                (data["LapNumber"] > lap - 5)
            ].copy() if p_minus2_driver is not None else data.iloc[0:0].copy()

            p_minus3 = data[
                (data["Driver"] == p_minus3_driver) &
                (data["LapNumber"] <= lap) &
                (data["LapNumber"] > lap - 5)
            ].copy() if p_minus3_driver is not None else data.iloc[0:0].copy()

            p_plus1 = data[
                (data["Driver"] == p_plus1_driver) &
                (data["LapNumber"] <= lap) &
                (data["LapNumber"] > lap - 5)
            ].copy() if p_plus1_driver is not None else data.iloc[0:0].copy()

            p_plus2 = data[
                (data["Driver"] == p_plus2_driver) &
                (data["LapNumber"] <= lap) &
                (data["LapNumber"] > lap - 5)
            ].copy() if p_plus2_driver is not None else data.iloc[0:0].copy()

            p_plus3 = data[
                (data["Driver"] == p_plus3_driver) &
                (data["LapNumber"] <= lap) &
                (data["LapNumber"] > lap - 5)
            ].copy() if p_plus3_driver is not None else data.iloc[0:0].copy()


            p_minus1_mean_LapTime = get_mean_lap_time(p_minus1)
            p_minus2_mean_LapTime = get_mean_lap_time(p_minus2)
            p_minus3_mean_LapTime = get_mean_lap_time(p_minus3)

            p_plus1_mean_LapTime = get_mean_lap_time(p_plus1)
            p_plus2_mean_LapTime = get_mean_lap_time(p_plus2)
            p_plus3_mean_LapTime = get_mean_lap_time(p_plus3)


            p_minus1_median_LapTime = get_median_lap_time(p_minus1)
            p_minus2_median_LapTime = get_median_lap_time(p_minus2)
            p_minus3_median_LapTime = get_median_lap_time(p_minus3)

            p_plus1_median_LapTime = get_median_lap_time(p_plus1)
            p_plus2_median_LapTime = get_median_lap_time(p_plus2)
            p_plus3_median_LapTime = get_median_lap_time(p_plus3)


            p_3_minus1 = p_minus1[
                p_minus1["LapNumber"] > lap - 3
            ]

            p_3_minus2 = p_minus2[
                p_minus2["LapNumber"] > lap - 3
            ]

            p_3_minus3 = p_minus3[
                p_minus3["LapNumber"] > lap - 3
            ]

            p_3_plus1 = p_plus1[
                p_plus1["LapNumber"] > lap - 3
            ]

            p_3_plus2 = p_plus2[
                p_plus2["LapNumber"] > lap - 3
            ]

            p_3_plus3 = p_plus3[
                p_plus3["LapNumber"] > lap - 3
            ]
            p_3_minus1_mean_LapTime = get_mean_lap_time(p_3_minus1)
            p_3_minus2_mean_LapTime = get_mean_lap_time(p_3_minus2)
            p_3_minus3_mean_LapTime = get_mean_lap_time(p_3_minus3)

            p_3_plus1_mean_LapTime = get_mean_lap_time(p_3_plus1)
            p_3_plus2_mean_LapTime = get_mean_lap_time(p_3_plus2)
            p_3_plus3_mean_LapTime = get_mean_lap_time(p_3_plus3)


            p_3_minus1_median_LapTime = get_median_lap_time(p_3_minus1)
            p_3_minus2_median_LapTime = get_median_lap_time(p_3_minus2)
            p_3_minus3_median_LapTime = get_median_lap_time(p_3_minus3)

            p_3_plus1_median_LapTime = get_median_lap_time(p_3_plus1)
            p_3_plus2_median_LapTime = get_median_lap_time(p_3_plus2)
            p_3_plus3_median_LapTime = get_median_lap_time(p_3_plus3)
            def get_last_lap_time(df):

                if df.empty:
                    return np.nan

                df = df.dropna(subset=["LapTime"])

                if df.empty:
                    return np.nan

                return df.sort_values("LapNumber")["LapTime"].iloc[-1]

            p_minus1_LapTime = get_last_lap_time(p_minus1)
            p_minus2_LapTime = get_last_lap_time(p_minus2)
            p_minus3_LapTime = get_last_lap_time(p_minus3)

            p_plus1_LapTime = get_last_lap_time(p_plus1)
            p_plus2_LapTime = get_last_lap_time(p_plus2)
            p_plus3_LapTime = get_last_lap_time(p_plus3)


            future = data[
                (data["LapNumber"] == lap + 5) &
                (data["Driver"] == driver)
            ]

            if future.empty:
                continue

            future_position = future["Position"].iloc[0]

            if pd.isna(future_position):
                continue

            target = Position - int(future_position)


            row = {
                "Driver": Driver,
                "Position": Position,
                "Time": Time,
                "Team": Team,
                "Compound": Compound,
                "TyreLife": TyreLife,
                "LapTime": LapTime,

                "p_minus1_mean_LapTime": p_minus1_mean_LapTime,
                "p_minus2_mean_LapTime": p_minus2_mean_LapTime,
                "p_minus3_mean_LapTime": p_minus3_mean_LapTime,

                "p_minus1_median_LapTime": p_minus1_median_LapTime,
                "p_minus2_median_LapTime": p_minus2_median_LapTime,
                "p_minus3_median_LapTime": p_minus3_median_LapTime,

                "p_plus1_mean_LapTime": p_plus1_mean_LapTime,
                "p_plus2_mean_LapTime": p_plus2_mean_LapTime,
                "p_plus3_mean_LapTime": p_plus3_mean_LapTime,

                "p_plus1_median_LapTime": p_plus1_median_LapTime,
                "p_plus2_median_LapTime": p_plus2_median_LapTime,
                "p_plus3_median_LapTime": p_plus3_median_LapTime,

                "p_3_minus1_mean_LapTime": p_3_minus1_mean_LapTime,
                "p_3_minus2_mean_LapTime": p_3_minus2_mean_LapTime,
                "p_3_minus3_mean_LapTime": p_3_minus3_mean_LapTime,

                "p_3_minus1_median_LapTime": p_3_minus1_median_LapTime,
                "p_3_minus2_median_LapTime": p_3_minus2_median_LapTime,
                "p_3_minus3_median_LapTime": p_3_minus3_median_LapTime,

                "p_3_plus1_mean_LapTime": p_3_plus1_mean_LapTime,
                "p_3_plus2_mean_LapTime": p_3_plus2_mean_LapTime,
                "p_3_plus3_mean_LapTime": p_3_plus3_mean_LapTime,

                "p_3_plus1_median_LapTime": p_3_plus1_median_LapTime,
                "p_3_plus2_median_LapTime": p_3_plus2_median_LapTime,
                "p_3_plus3_median_LapTime": p_3_plus3_median_LapTime,

                "p_minus1_LapTime": p_minus1_LapTime,
                "p_minus2_LapTime": p_minus2_LapTime,
                "p_minus3_LapTime": p_minus3_LapTime,

                "p_plus1_LapTime": p_plus1_LapTime,
                "p_plus2_LapTime": p_plus2_LapTime,
                "p_plus3_LapTime": p_plus3_LapTime,

                "target": target
            }

            rows.append(row)

    return pd.DataFrame(rows)

In [14]:
datasets = []

for i in df["Season"].unique():
    for j in df.loc[df["Season"] == i, "Round"].unique():

        sdf = df[
            (df["Season"] == i) &
            (df["Round"] == j)
        ].copy()

        datasets.append(create_data_for_round(sdf))

dataset = pd.concat(datasets, ignore_index=True)

In [15]:
sdf = df[
    (df["Season"] == 2025) &
    (df["Round"] == 1)
].copy()

test = create_data_for_round(sdf)

In [16]:
test.isna().sum()

Driver                         0
Position                       0
Time                           0
Team                           0
Compound                       0
TyreLife                       0
LapTime                        0
p_minus1_mean_LapTime         68
p_minus2_mean_LapTime        101
p_minus3_mean_LapTime        139
p_minus1_median_LapTime       68
p_minus2_median_LapTime      101
p_minus3_median_LapTime      139
p_plus1_mean_LapTime          58
p_plus2_mean_LapTime          96
p_plus3_mean_LapTime         125
p_plus1_median_LapTime        58
p_plus2_median_LapTime        96
p_plus3_median_LapTime       125
p_3_minus1_mean_LapTime       68
p_3_minus2_mean_LapTime      101
p_3_minus3_mean_LapTime      139
p_3_minus1_median_LapTime     68
p_3_minus2_median_LapTime    101
p_3_minus3_median_LapTime    139
p_3_plus1_mean_LapTime        58
p_3_plus2_mean_LapTime        96
p_3_plus3_mean_LapTime       125
p_3_plus1_median_LapTime      58
p_3_plus2_median_LapTime      96
p_3_plus3_median_LapTime     125
p_minus1_LapTime              68
p_minus2_LapTime             101
p_minus3_LapTime             139
p_plus1_LapTime               58
p_plus2_LapTime               96
p_plus3_LapTime              125
target                         0
dtype: int64

In [18]:
dataset.shape

(87908, 38)

In [17]:
dataset.isnull().sum()

Driver                           0
Position                         0
Time                             0
Team                             0
Compound                         0
TyreLife                       631
LapTime                        116
p_minus1_mean_LapTime         7816
p_minus2_mean_LapTime        12571
p_minus3_mean_LapTime        17308
p_minus1_median_LapTime       7816
p_minus2_median_LapTime      12571
p_minus3_median_LapTime      17308
p_plus1_mean_LapTime          7151
p_plus2_mean_LapTime         11302
p_plus3_mean_LapTime         15727
p_plus1_median_LapTime        7151
p_plus2_median_LapTime       11302
p_plus3_median_LapTime       15727
p_3_minus1_mean_LapTime       7827
p_3_minus2_mean_LapTime      12590
p_3_minus3_mean_LapTime      17323
p_3_minus1_median_LapTime     7827
p_3_minus2_median_LapTime    12590
p_3_minus3_median_LapTime    17323
p_3_plus1_mean_LapTime        7161
p_3_plus2_mean_LapTime       11309
p_3_plus3_mean_LapTime       15734
p_3_plus1_median_LapTime      7161
p_3_plus2_median_LapTime     11309
p_3_plus3_median_LapTime     15734
p_minus1_LapTime              7816
p_minus2_LapTime             12571
p_minus3_LapTime             17308
p_plus1_LapTime               7151
p_plus2_LapTime              11302
p_plus3_LapTime              15727
target                           0
dtype: int64

In [20]:
dataset.dropna().shape

(49653, 38)

In [21]:
dataset

,Driver,Position,Time,Team,Compound,TyreLife,LapTime,p_minus1_mean_LapTime,p_minus2_mean_LapTime,p_minus3_mean_LapTime,...,p_3_plus1_median_LapTime,p_3_plus2_median_LapTime,p_3_plus3_median_LapTime,p_minus1_LapTime,p_minus2_LapTime,p_minus3_LapTime,p_plus1_LapTime,p_plus2_LapTime,p_plus3_LapTime,target
0,VER,1,375.957,Red Bull Racing,MEDIUM,5.0,93.955,NaN,NaN,NaN,...,94.055,94.549,94.557,NaN,NaN,NaN,94.085,94.382,94.557,-1
1,PER,2,378.418,Red Bull Racing,MEDIUM,5.0,94.085,94.2924,NaN,NaN,...,94.549,94.557,94.512,93.955,NaN,NaN,94.382,94.557,94.512,-2
2,ALO,5,382.423,Aston Martin,MEDIUM,6.0,94.512,95.4624,95.0008,94.7846,...,94.902,95.150,95.184,94.557,94.382,94.085,94.902,95.150,95.107,-2
3,LEC,3,379.499,Ferrari,MEDIUM,5.0,94.382,94.7846,94.2924,NaN,...,94.557,94.512,94.902,94.085,93.955,NaN,94.557,94.512,94.902,-2
4,SAR,18,397.992,Williams,MEDIUM,5.0,96.204,98.5916,98.4108,98.2200,...,96.526,NaN,NaN,96.244,96.003,95.699,96.238,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87903,SAI,4,5131.386,McLaren,MEDIUM,27.0,57.648,57.5310,57.5772,57.1408,...,57.262,57.278,57.105,57.554,57.557,57.394,57.492,57.339,57.448,0
87904,RAI,14,5142.633,Alfa Romeo Racing,SOFT,20.0,57.870,56.2410,57.7878,57.6944,...,58.202,58.018,58.690,56.777,57.750,57.670,58.202,58.012,59.696,0
87905,BOT,8,5134.645,Mercedes,HARD,33.0,57.198,57.4212,57.3148,57.4236,...,57.362,57.356,57.670,57.448,57.339,57.492,57.590,57.356,57.670,0
87906,AIT,16,5150.205,Williams,SOFT,23.0,58.012,58.3760,57.9630,56.2410,...,58.690,NaN,NaN,58.202,57.870,56.777,59.696,NaN,NaN,0
87907,GIO,12,5140.825,Alfa Romeo Racing,MEDIUM,28.0,57.750,57.6944,57.5658,57.5574,...,56.542,57.870,58.202,57.670,57.356,57.590,56.777,57.870,58.202,-1

In [24]:
dataset.to_csv("../data/model1_dataset.csv")